Develop
DeuSsd/todo-app pull request #1
Opened 2022-05-04 17:44 UTC by DeuSsd

2022-05-04 20:23 UTC, vladefr97 requested changes

2022-05-04 20:23 UTC, vladefr97 commented on todo_service/todo/templates/todo/todo.html
> +        <div class="todo__body__background">  <!--  table -->
Название класса не по БЭМ

2022-05-04 20:23 UTC, vladefr97 commented on todo_service/todo/templates/todo/todo.html
> +            <div class="todo__body__filter">  <!-- Table-row -->
Класс не по БЭМ

2022-05-04 20:23 UTC, vladefr97 commented on todo_service/todo/templates/todo/todo.html
> +    <!-- <link rel = "stylesheet" type = "text/css" href = "css/styles.css"> -->
Для чистоты кода закоменченный код лучше удалять

2022-05-04 20:23 UTC, vladefr97 commented on todo_service/todo/views.py
> +            'post': serializer.data,
Зачем возвращать в post те же данные, что и пришли? можно же просто статус запроса возвращать

2022-05-04 20:23 UTC, vladefr97 commented on todo_service/todo/static/todo/js/base.js
> +        <div class="edit__mode">
Дать названия css классов по БЭМ

2022-05-04 20:23 UTC, vladefr97 commented on todo_service/todo/static/todo/js/base.js
> +function getTaskAttributes_ADVANCEDMODE(id){
Код внутри данной функции дублируется с кодом функции выше, нужно оптимизировать, возможно, вынести дублирующийся код в отдельную функцию

2022-05-04 20:23 UTC, vladefr97 commented on todo_service/todo/static/todo/js/base.js
> +function getTaskAttributes_EDITMODE(id){
Почему в названии функции используется camelCase, snake_case и CAPSLOCK?

2022-05-04 20:23 UTC, vladefr97 commented on todo_service/todo/static/todo/js/base.js
> +function button_done_ADVANCEDMODE(id) {
Сделать название в snakeCase (для функций далее тоже справедливо)

2022-05-04 20:23 UTC, vladefr97 commented on todo_service/todo/static/todo/js/base.js
> +function button_cancel_EDITMODE(id) {
Код дублируется в четырех функция, нужно сделать рефакторинг. Возможно, стоит завесить переменную mode, чтобы не делать дублирований.

2022-05-08 19:22 UTC, DeuSsd commented on todo_service/todo/static/todo/js/base.js
> +function button_done_ADVANCEDMODE(id) {
Согласен, названия должны быть стандартизированы, но в данном случае не считаю плохой практикой использовать данный формат нейминга, так как он позволяет визуально выделить данные функции от остальных.

2022-05-08 19:58 UTC, DeuSsd commented on todo_service/todo/static/todo/js/base.js
> +function getTaskAttributes_ADVANCEDMODE(id){
И правда как-то я проглядел, там всего 1 строчка меняется

2022-05-11 20:08 UTC, vladefr97 approved these changes

2022-05-11 20:08 UTC, vladefr97 commented on todo_service/todo/static/todo/css/todo_body/task/task_advanced_mode.css
> +.task__advanced_mode_button_done button:active{
Какие-то мега сложные названия классов и не по БЭМ
![Снимок экрана 2022-05-11 в 22 52 30](https://user-images.githubusercontent.com/30003115/167934190-ffb8b139-e779-4ee0-8324-0a7d8e028e45.png)
М

2022-05-11 20:08 UTC, vladefr97 commented on todo_service/todo/static/todo/js/base.js
> +function button_done_ADVANCEDMODE(id) {
А для чего нужно визуально выделять именно эти функции, они чем-то важнее других? Если появятся более важные функции, то их тоже по такой логике нужно будет как-то выделить)
Можешь уже оставить так, но я бы все в едином стиле именовал, иначе такие штуки могут отвлекать внимание на несущественные в рамках кода вещи, а важные части кода будут теряться.

2022-05-11 20:09 UTC, merged

2022-05-11 20:21 UTC, DeuSsd commented on todo_service/todo/static/todo/js/base.js
> +function button_done_ADVANCEDMODE(id) {
Я тут подумал и понял, что функции это действия поэтому как насчёт такого названия: ```clickEventAdvanceModeButtonDone()```, но тогда название мега длинное или как вариант: ```clickEventButtonDone_AdvanceMode()``` , более читабельно, так что как быть?

2022-05-11 20:38 UTC, vladefr97 commented on todo_service/todo/static/todo/js/base.js
> +function button_done_ADVANCEDMODE(id) {
clickEventAdvanceModeButtonDone - можно убрать из названия слово Event, итак понятно, что click это событие (Event).

Могу такие варианты предложить: 
onAdvanceModeDoneButtonClick - для обработчиков событий можно начинать названия с on...
advancedModeDoneButtonClicked - можно назвать глаголом прошедшего времени

Но в целом не очень красиво, что везде повторяется advanceMode, editMode, прослеживается дублирование кода опять же. Тут уже проблемы с логикой кода. Можно mode передавать в качестве аргумента в функции, например. Тогда не нужно будет везде дублировать это словосочетание. 
Вообще в длинных названиях функций/переменных нет ничего плохого, если такое название дает ясно понять какую задачу выполняет функция/переменная и это название больше нельзя сократить.